MiNiFi Config Version: 2
Flow Controller:
  name: SensorWeatherDataEdgeOffice
  comment: ''
Core Properties:
  flow controller graceful shutdown period: 10 sec
  flow service write delay interval: 500 ms
  administrative yield duration: 30 sec
  bored yield duration: 10 millis
  max concurrent threads: 1
FlowFile Repository:
  partitions: 256
  checkpoint interval: 2 mins
  always sync: false
  Swap:
    threshold: 20000
    in period: 5 sec
    in threads: 1
    out period: 5 sec
    out threads: 4
Content Repository:
  content claim max appendable size: 10 MB
  content claim max flow files: 100
  always sync: false
Provenance Repository:
  provenance rollover time: 1 min
Component Status Repository:
  buffer size: 1440
  snapshot frequency: 1 min
Security Properties:
  keystore: ''
  keystore type: ''
  keystore password: ''
  key password: ''
  truststore: ''
  truststore type: ''
  truststore password: ''
  ssl protocol: ''
  Sensitive Props:
    key:
    algorithm: PBEWITHMD5AND256BITAES-CBC-OPENSSL
    provider: BC
Processors:
- id: bb3789f8-015a-1000-0000-000000000000
  name: ExecuteProcess
  class: org.apache.nifi.processors.standard.ExecuteProcess
  max concurrent tasks: 1
  scheduling strategy: TIMER_DRIVEN
  scheduling period: 1 sec
  penalization period: 30 sec
  yield period: 1 sec
  run duration nanos: 0
  auto-terminated relationships list: []
  Properties:
    Argument Delimiter: ' '
    Batch Duration: 5 sec
    Command: sh
    Command Arguments: /home/pi/sensor_readings.sh
    Redirect Error Stream: 'false'
Process Groups: []
Input Ports: []
Output Ports: []
Funnels: []
Connections:
- id: b76bd734-015b-1000-0000-000000000000
  name: ExecuteProcess/success/479b7c3d-0159-1000-b6b3-478c0588a810
  source id: bb3789f8-015a-1000-0000-000000000000
  source relationship names:
  - success
  destination id: 479b7c3d-0159-1000-b6b3-478c0588a810
  max work queue size: 10000
  max work queue data size: 1 GB
  flowfile expiration: 0 sec
  queue prioritizer class: ''
Remote Process Groups:
- id: bb39ea97-015a-1000-0000-000000000000
  name: ''
  url: http://10.11.4.120:19090/nifi/
  comment: ''
  timeout: 30 sec
  yield period: 10 sec
  transport protocol: RAW
  Input Ports:
  - id: 479b7c3d-0159-1000-b6b3-478c0588a810
    name: IngestSensorReadings
    comment: ''
    max concurrent tasks: 1
    use compression: false
